### ISSUE TITLE
Would it be possible to filter the Markdown (plain text) to remove some "markdown-isms"?

### ISSUE THREAD

**Issue by walterdavis** [zombocom/maildown#57]
It would be nice if there was a way to filter out some (but not all) of the Markdown syntax from the plain text that gets sent in the mail. For example:

```
## This is a call to action

Please [click here](http://example.com) to learn more.

* Reasons why
* Reasons why
* Reasons why

```

might become
```
This is a call to action

Please click here: http://example.com to learn more.

* Reasons why
* Reasons why
* Reasons why
```

It's a subtle thing, and it would take some design thinking to ensure that we don't strip away too much of the meaning (inline stuff like bold and italic would need to remain, I think) but it could make the text reading experience better.

Or, am I missing something, and this is already happening? I have used this in a couple of projects in the past, and it always seemed to me that the raw Markdown was being served (with its ERB context filled in, naturally).

Thoughts?

**Comment by schneems** [comment]
You can configure your handler for text here https://github.com/codetriage/maildown#configure-markdown-renderer it might be possible to configure this behavior there (but I don’t know)

**Comment by schneems** [comment]
It's been awhile If you figured this out please post back to let others know.
